"""领域内核：不依赖 IO、网络、浏览器与任何第三方库。

任何层都可以 import ``dailytask.core``；``dailytask.core`` 不 import 任何其它
``dailytask`` 子包。这条单向依赖是整个重构的地基——它保证结论模型、账号模型与
流程模型可以被 CLI、GUI、CI 汇总、测试各自独立使用，不会像旧 ``providers/base.py``
那样把 HTTP、重试、额度换算、文本匹配和数据模型糊在同一个 943 行模块里。
"""

from __future__ import annotations

from .account import (
    CREDENTIAL_FIELDS,
    CREDENTIAL_GROUPS,
    AccountSpec,
    CredentialSet,
    LoginSpec,
    NetworkSpec,
    PolicySpec,
    ResolvedAccount,
    TaskSpec,
    normalize_base_url,
    slug_seed,
    slugify,
)
from .errors import (
    ConfigError,
    LoginRequired,
    NotApplicable,
    TaskError,
    TemplateError,
    TransientError,
    VerificationRequired,
)
from .flow import AUTO, OFF, Discovery, FlowPlan, StageMode, StagePlan
from .manifest import (
    EMPTY_SCHEMA,
    STAGES,
    UNITS,
    ArgSchema,
    ArgSpec,
    DetectSpec,
    DisplayDefaults,
    LoginOption,
    ResponseMap,
    TaskOption,
    TemplateManifest,
)
from .outcome import (
    OK_VERDICTS,
    REASONS,
    DisplaySpec,
    Evidence,
    Outcome,
    ReasonSpec,
    Verdict,
    already_done,
    blocked,
    failed,
    from_legacy_status,
    need_config,
    need_login,
    need_verification,
    network_error,
    no_effect,
    not_applicable,
    success,
    to_legacy_status,
)

__all__ = [
    "AUTO",
    "OFF",
    "STAGES",
    "UNITS",
    "OK_VERDICTS",
    "REASONS",
    "EMPTY_SCHEMA",
    "CREDENTIAL_FIELDS",
    "CREDENTIAL_GROUPS",
    "AccountSpec",
    "ArgSchema",
    "ArgSpec",
    "ConfigError",
    "CredentialSet",
    "DetectSpec",
    "Discovery",
    "DisplayDefaults",
    "DisplaySpec",
    "Evidence",
    "FlowPlan",
    "LoginOption",
    "LoginRequired",
    "LoginSpec",
    "NetworkSpec",
    "NotApplicable",
    "Outcome",
    "PolicySpec",
    "ReasonSpec",
    "ResolvedAccount",
    "ResponseMap",
    "StageMode",
    "StagePlan",
    "TaskError",
    "TaskOption",
    "TaskSpec",
    "TemplateError",
    "TemplateManifest",
    "TransientError",
    "Verdict",
    "VerificationRequired",
    "already_done",
    "blocked",
    "failed",
    "from_legacy_status",
    "need_config",
    "need_login",
    "need_verification",
    "network_error",
    "no_effect",
    "not_applicable",
    "normalize_base_url",
    "slug_seed",
    "slugify",
    "success",
    "to_legacy_status",
]
